version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- pwsh: >-
    $url = "http://speed.transip.nl/10mb.bin"

    $dest = "InstallerProjects.vsix"

    Invoke-WebRequest -Uri $url -OutFile $dest

    $VSInstallDir = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service"

    $VsixLocation = "InstallerProjects.vsix"

    Start-Process -Filepath "$($VSInstallDir)\VSIXInstaller" -ArgumentList "/q /a $($VsixLocation)" -Wait
before_build:
- pwsh: dotnet restore
build:
  project: GitTank.sln
  publish_core_console: true
  parallel: true
  verbosity: minimal
before_package:
- pwsh: dotnet build
after_build:
- pwsh: dotnet publish
after_test:
- pwsh: dotnet test
artifacts:
- path: GitTank\bin\$(configuration)\net6.0-windows10.0.22000.0\publish
  name: $(APPVEYOR_PROJECT_SLUG)-$(APPVEYOR_BUILD_VERSION)
