version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: dotnet restore
build_script:
- pwsh: dotnet build
after_build:
- pwsh: dotnet publish
test_script:
- pwsh: dotnet test
after_test:
- pwsh: echo "Upload test report"
artifacts:
- path: GitTank\bin\$(configuration)\net6.0-windows10.0.22000.0\publish
  name: $(APPVEYOR_PROJECT_SLUG)-$(APPVEYOR_BUILD_VERSION)
