version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: dotnet restore
build_script:
- pwsh: dotnet build --no-restore 
after_build:
- pwsh: dotnet publish --no-build --no-restore 
before_test:
  - cd GitTank.Tests
  - nuget install Appveyor.TestLogger
  - cd ..
test_script:
- pwsh: dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor
after_test:
# - pwsh: >-
#     $ProgressPreference = 'SilentlyContinue'
    
#     Invoke-WebRequest -Uri https://keybase.io/codecovsecurity/pgp_keys.asc -OutFile codecov.asc 
    
#     gpg.exe --import codecov.asc

#     Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    
#     Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe.SHA256SUM -Outfile codecov.exe.SHA256SUM
    
#     Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe.SHA256SUM.sig -Outfile codecov.exe.SHA256SUM.sig

#     gpg.exe --verify codecov.exe.SHA256SUM.sig codecov.exe.SHA256SUM
    
#     If ($(Compare-Object -ReferenceObject  $(($(certUtil -hashfile codecov.exe SHA256)[1], "codecov.exe") -join "  ") -DifferenceObject $(Get-Content codecov.exe.SHA256SUM)).length -eq 0) { echo "SHASUM verified" } Else {exit 1}
- pwsh: >-
    $ProgressPreference = "SilentlyContinue"

    Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe

    .\codecov.exe
artifacts:
- path: GitTank\bin\$(configuration)\net6.0-windows10.0.22000.0\publish
  name: $(APPVEYOR_PROJECT_SLUG)-$(APPVEYOR_BUILD_VERSION)
