version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- pwsh: choco install opencover.portable
- pwsh: choco install codecov
before_build:
- pwsh: dotnet restore
build_script:
- pwsh: dotnet build --no-restore
after_build:
- pwsh: dotnet publish --no-build --no-restore
before_test:
  - cd GitTank.Tests
  - nuget install Appveyor.TestLogger
  - cd ..
test_script:
- pwsh: dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor
after_test:
- pwsh: OpenCover.Console.exe -register:user -target:dotnet -targetargs:"test --no-restore --no-build --logger:trx" -filter:"+[*]* -[*.Tests*]*" -oldStyle -output:TestCoverage.xml
- pwsh: . codecov -f TestCoverage.xml
artifacts:
- path: GitTank\bin\$(configuration)\net6.0-windows10.0.22000.0\publish
  name: $(APPVEYOR_PROJECT_SLUG)-$(APPVEYOR_BUILD_VERSION)
